openapi: 3.2.0
info:
  title: Plex Media Server Play Queue API
  version: '1.2.2

    '
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: '# API Info

    ## Content Types

    The API supports responses in both XML and JSON, and clients can request one or the other using the standard `Accept` HTTP header.'
servers:
- url: https://{IP-description}.{identifier}.plex.direct:{port}
  variables:
    IP-description:
      default: 1-2-3-4
      description: A `-` separated string of the IPv4 or IPv6 address components
    identifier:
      default: 0123456789abcdef0123456789abcdef
      description: The unique identifier of this particular PMS
    port:
      default: '32400'
security:
- user_token:
  - shared user
  - admin
tags:
- name: Play Queue
  description: 'The playqueue feature within a media provider

    A play queue represents the current list of media for playback.'
paths:
  /playQueues:
    post:
      tags:
      - Play Queue
      summary: Create a play queue
      description: 'Makes a new play queue for a device. The source of the playqueue can either be a URI, or a playlist. The response is a media container with the initial items in the queue. Each item in the queue will be a regular item but with `playQueueItemID` - a unique ID since the queue could have repeated items with the same `ratingKey`.

        Note: Either `uri` or `playlistID` must be specified'
      operationId: playQueuePostSlash
      parameters:
      - in: query
        name: uri
        schema:
          type: string
        description: The content URI for what we're playing.
      - in: query
        name: playlistID
        schema:
          type: integer
        description: the ID of the playlist we're playing.
      - in: query
        name: type
        schema:
          type: string
          enum:
          - audio
          - video
          - photo
        required: true
        description: The type of play queue to create
      - in: query
        name: key
        schema:
          type: string
        description: The key of the first item to play, defaults to the first in the play queue.
      - in: query
        name: shuffle
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Whether to shuffle the playlist, defaults to 0.
      - in: query
        name: repeat
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: If the PQ is bigger than the window, fill any empty space with wraparound items, defaults to 0.
      - in: query
        name: continuous
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Whether to create a continuous play queue (e.g. from an episode), defaults to 0.
      - in: query
        name: extrasPrefixCount
        schema:
          type: integer
        description: Number of trailers to prepend a movie with not including the pre-roll. If omitted the pre-roll will not be returned in the play queue. When resuming a movie `extrasPrefixCount` should be omitted as a parameter instead of passing 0.
      - in: query
        name: recursive
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Only applies to queues of type photo, whether to retrieve all descendent photos from an album or section, defaults to 1.
      - in: query
        name: onDeck
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Only applies to queues of type show or seasons, whether to return a queue that is started on the On Deck episode if one exists. Otherwise begins the play queue on the beginning of the show or season.
      responses:
        '200':
          description: OK
          headers:
            X-Plex-Container-Total-Size:
              description: Provided on all MediaContainer objects indicating the total size of objects available
              schema:
                type: integer
            X-Plex-Container-Start:
              description: Provided on all MediaContainer objects indicating the offset of where this container page starts
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: object
                properties:
                  MediaContainer:
                    allOf:
                    - $ref: '#/components/schemas/properties-MediaContainer'
                    - type: object
                      properties:
                        playQueueID:
                          type: integer
                          description: The ID of the play queue, which is used in subsequent requests.
                        playQueueSelectedItemID:
                          type: integer
                          description: The queue item ID of the currently selected  item.
                        playQueueSelectedItemOffset:
                          type: integer
                          description: The offset of the selected item in the play queue, from the beginning of the queue.
                        playQueueSelectedMetadataItemID:
                          type: integer
                          description: The metadata item ID of the currently selected item (matches `ratingKey` attribute in metadata item if the media provider is a library).
                        playQueueShuffled:
                          type: boolean
                          description: Whether or not the queue is shuffled.
                        playQueueSourceURI:
                          type: string
                          description: The original URI used to create the play queue.
                        playQueueTotalCount:
                          type: integer
                          description: The total number of items in the play queue.
                        playQueueVersion:
                          type: integer
                          description: The version of the play queue. It increments every time a change is made to the play queue to assist clients in knowing when to refresh.
                        playQueueLastAddedItemID:
                          type: string
                          description: Defines where the "Up Next" region starts
              examples:
                playQueue:
                  description: A play queue
                  value:
                    MediaContainer:
                      playQueueID: 9631
                      playQueueSelectedItemID: 2211762
                      playQueueSelectedItemOffset: 0
                      playQueueSelectedMetadataItemID: 1941458
                      playQueueShuffled: false
                      playQueueSourceURI: library://2d8ea42e-7845-498b-b349-095ecaa3c451/item/%2Flibrary%2Fmetadata%2F1906642
                      playQueueTotalCount: 22
                      playQueueVersion: 1
                      size: 21
                      Metadata:
                      - playQueueItemID: 2211762
                        restOf: metadataHere
        '400':
          $ref: '#/components/responses/400'
  /playQueues/{playQueueId}:
    get:
      tags:
      - Play Queue
      summary: Retrieve a play queue
      description: Retrieves the play queue, centered at current item. This can be treated as a regular container by play queue-oblivious clients, but they may wish to request a large window onto the queue since they won't know to refresh.
      operationId: playQueueQueueGetSlash
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        required: true
        description: The ID of the play queue.
      - in: query
        name: own
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: If the server should transfer ownership to the requesting client (used in remote control scenarios).
      - in: query
        name: center
        schema:
          type: string
        description: The play queue item ID for the center of the window - this doesn't change the current selected item.
      - in: query
        name: window
        schema:
          type: integer
        description: How many items on each side of the center of the window
      - in: query
        name: includeBefore
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Whether to include the items before the center (if 0, center is not included either), defaults to 1.
      - in: query
        name: includeAfter
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Whether to include the items after the center (if 0, center is not included either), defaults to 1.
      responses:
        '200':
          $ref: '#/components/responses/slash-post-responses-200'
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
    put:
      tags:
      - Play Queue
      summary: Add a generator or playlist to a play queue
      operationId: playQueueQueuePutSlash
      description: Adds an item to a play queue (e.g. party mode). Increments the version of the play queue. Takes the following parameters (`uri` and `playlistID` are mutually exclusive). Returns the modified play queue.
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        required: true
        description: The ID of the play queue.
      - in: query
        name: uri
        schema:
          type: string
        description: The content URI for what we're adding to the queue.
      - in: query
        name: playlistID
        schema:
          type: string
        description: The ID of the playlist to add to the playQueue.
      - in: query
        name: next
        schema:
          type: integer
          enum:
          - 0
          - 1
        description: Play this item next (defaults to 0 - queueing at the end of manually queued items).
      responses:
        '200':
          $ref: '#/components/responses/slash-post-responses-200'
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
  /playQueues/{playQueueId}/items:
    delete:
      tags:
      - Play Queue
      summary: Clear a play queue
      operationId: playQueueQueueDeleteItems
      description: Deletes all items in the play queue, and increases the version of the play queue.
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        description: The ID of the play queue.
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mediaContainerWithPlaylistMetadata'
              examples:
                playQueue:
                  description: An empty play queue
                  value:
                    MediaContainer:
                      playQueueID: 9631
                      playQueueSelectedItemID: 2211762
                      playQueueSelectedItemOffset: 0
                      playQueueSelectedMetadataItemID: 1941458
                      playQueueShuffled: false
                      playQueueTotalCount: 0
                      playQueueVersion: 2
                      size: 0
  /playQueues/{playQueueId}/items/{playQueueItemId}:
    delete:
      tags:
      - Play Queue
      summary: Delete an item from a play queue
      operationId: playQueueQueueDeleteItemsItem
      description: Deletes an item in a play queue. Increments the version of the play queue. Returns the modified play queue.
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        description: The ID of the play queue.
        required: true
      - in: path
        name: playQueueItemId
        schema:
          type: integer
        description: The play queue item ID to delete.
        required: true
      responses:
        '200':
          $ref: '#/components/responses/slash-post-responses-200'
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
  /playQueues/{playQueueId}/items/{playQueueItemId}/move:
    put:
      tags:
      - Play Queue
      summary: Move an item in a play queue
      operationId: playQueueQueuePutItemsMove
      description: Moves an item in a play queue, and increases the version of the play queue. Returns the modified play queue.
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        description: The ID of the play queue.
        required: true
      - in: path
        name: playQueueItemId
        schema:
          type: integer
        description: The play queue item ID to delete.
        required: true
      - in: query
        name: after
        schema:
          type: integer
        description: The play queue item ID to insert the new item after. If not present, moves to the beginning.
      responses:
        '200':
          $ref: '#/components/responses/slash-post-responses-200'
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue or queue item not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
  /playQueues/{playQueueId}/reset:
    put:
      tags:
      - Play Queue
      summary: Reset a play queue
      operationId: playQueuePlayQueueReset
      description: Reset a play queue to the first item being the current item
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        description: The ID of the play queue.
        required: true
      responses:
        '200':
          $ref: '#/components/responses/slash-post-responses-200'
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
  /playQueues/{playQueueId}/shuffle:
    put:
      tags:
      - Play Queue
      summary: Shuffle a play queue
      operationId: playQueueQueuePutItemsShuffle
      description: Shuffle a play queue (or reshuffles if already shuffled). The currently selected item is maintained. Note that this is currently only supported for play queues *without* an Up Next area. Returns the modified play queue.
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        description: The ID of the play queue.
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mediaContainerWithPlaylistMetadata'
              examples:
                playQueue:
                  description: A shuffled play queue
                  value:
                    MediaContainer:
                      playQueueID: 9631
                      playQueueSelectedItemID: 2211762
                      playQueueSelectedItemOffset: 0
                      playQueueSelectedMetadataItemID: 1941458
                      playQueueShuffled: true
                      playQueueSourceURI: library://2d8ea42e-7845-498b-b349-095ecaa3c451/item/%2Flibrary%2Fmetadata%2F1906642
                      playQueueTotalCount: 22
                      playQueueVersion: 1
                      size: 21
                      Metadata:
                      - playQueueItemID: 2211762
                        restOf: metadataHere
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue not found or current item not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
  /playQueues/{playQueueId}/unshuffle:
    put:
      tags:
      - Play Queue
      summary: Unshuffle a play queue
      operationId: playQueueQueuePutItemsUnshuffle
      description: Unshuffles a play queue and restores "natural order". Note that this is currently only supported for play queues *without* an Up Next area. Returns the modified play queue.
      parameters:
      - in: path
        name: playQueueId
        schema:
          type: integer
        description: The ID of the play queue.
        required: true
      responses:
        '200':
          $ref: '#/components/responses/slash-post-responses-200'
        '400':
          $ref: '#/components/responses/400'
        '404':
          description: Play queue not found or current item not found
          content:
            text/html:
              examples:
                notFound:
                  summary: Not Found
                  value: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
components:
  schemas:
    sort:
      allOf:
      - $ref: '#/components/schemas/directory'
      - type: object
        description: 'Each `Sort` object contains a description of the sort field.

          '
        properties:
          defaultDirection:
            type: string
            enum:
            - asc
            - desc
            description: This default diction of this sort
          default:
            type: string
            enum:
            - asc
            - desc
            description: If present, this sort is the default and in this direction
          key:
            type: string
            description: The key to use in the sort field to make items sort by this item
          descKey:
            type: string
            description: The key for sorting this field in reverse order
          title:
            type: string
            description: The title of the field.
          firstCharacterKey:
            type: string
            description: The key to use to get items sorted by this field and indexed by the first character
    part:
      description: '`Part` represents a particular file or "part" of a media item. The part is the playable unit of the media hierarchy. Suppose that a movie library contains a movie that is broken up into files, reminiscent of a movie split across two BDs. The metadata item represents information about the movie, the media item represents this instance of the movie at this resolution and quality, and the part items represent the two playable files.  If another media were added which contained the joining of these two parts transcoded down to a lower resolution, then this metadata would contain 2 medias, one with 2 parts and one with 1 part.

        '
      type: object
      properties:
        audioProfile:
          example: lc
        container:
          description: The container of the media file, such as `mp4` or `mkv`
          example: mov
        duration:
          type: integer
          description: The duration of the media item, in milliseconds
          example: 150192
        file:
          description: The local file path at which the part is stored on the server
          example: /home/schuyler/Videos/Trailers/Cloud Atlas (2012).mov
        has64bitOffsets:
          type: boolean
          example: false
        id:
          type: integer
          example: 1
        key:
          description: The key from which the media can be streamed
          example: /library/parts/1/1531779263/file.mov
        optimizedForStreaming:
          type: boolean
          example: false
        size:
          type: integer
          description: The size of the media, in bytes
          example: 105355654
        videoProfile:
          example: main
        Stream:
          type: array
          items:
            $ref: '#/components/schemas/stream'
      additionalProperties: true
    media:
      description: '`Media` represents an one or more media files (parts) and is a child of a metadata item. There aren''t necessarily any guaranteed attributes on media elements since the attributes will vary based on the type. The possible attributes are not documented here, but they typically have self-evident names. High-level media information that can be used for badging and flagging, such as `videoResolution` and codecs, is included on the media element.

        '
      type: object
      properties:
        aspectRatio:
          type: number
          example: 2.35
        audioChannels:
          type: integer
          example: 2
        audioCodec:
          example: aac
        audioProfile:
          example: lc
        bitrate:
          type: integer
          example: 5612
        container:
          example: mov
        duration:
          type: integer
          example: 150192
        has64bitOffsets:
          type: boolean
          example: false
        hasVoiceActivity:
          type: boolean
          example: true
        height:
          type: integer
          example: 544
        id:
          type: integer
          example: 1
        optimizedForStreaming:
          type: boolean
          example: false
        videoCodec:
          example: h264
        videoFrameRate:
          example: 24p
        videoProfile:
          example: main
        videoResolution:
          example: '720'
        width:
          type: integer
          example: 1280
        Part:
          type: array
          items:
            $ref: '#/components/schemas/part'
      additionalProperties: true
    filter:
      allOf:
      - $ref: '#/components/schemas/directory'
      - type: object
        description: 'Each `Filter` object contains a description of the filter. Note that it is not an exhaustive list of the full media query language, but an important subset useful for top-level API.

          '
        properties:
          filter:
            type: string
            description: This represents the filter name used for the filter, which can be used to construct complex media queries with.
          filterType:
            type: string
            description: This is either `string`, `integer`, or `boolean`, and describes the type of values used for the filter.
          key:
            type: string
            description: This provides the endpoint where the possible range of values for the filter can be retrieved (e.g. for a "Genre" filter, it returns a list of all the genres in the library). This will include a `type` argument that matches the metadata type of the Type element.
          title:
            type: string
            description: The title for the filter.
    metadata:
      description: 'Items in a library are referred to as "metadata items." These metadata items are distinct from "media items" which represent actual instances of media that can be consumed. Consider a TV library that has a single video file in it for a particular episode of a show. The library has a single media item, but it has three metadata items: one for the show, one for the season, and one for the episode. Consider a movie library that has two video files in it: the same movie, but two different resolutions. The library has a single metadata item for the movie, but that metadata item has two media items, one for each resolution. Additionally a "media item" will have one or more "media parts" where the the parts are intended to be watched together, such as a CD1 and CD2 parts of the same movie.


        Note that when a metadata item has multiple media items, those media items should be isomorphic. That is, a 4K version and 1080p version of a movie are different versions of the same movie. They have the same duration, same summary, same rating, etc. and they can generally be considered interchangeable. A theatrical release vs. director''s cut vs. unrated version on the other hand would be separate metadata items.


        Metadata items can often live in a hierarchy with relationships between them.  For example, the metadata item for an episodes is associated with a season metadata item which is associated with a show metadata item.  A similar hierarchy exists with track, album, and artist and photos and photo album.  The relationships may be expressed via relative terms and absolute terms.  For example, "leaves" refer to metadata items which has associated media (there is no media for a season nor show).  A show will have "children" in the form of seasons and a season will have "children" in the form of episodes and episodes have "parent" in the form of a season which has a "parent" in the form of a show.  Similarly, a show has "grandchildren" in the form of episodse and an episode has a "grandparent" in the form of a show.

        '
      type: object
      properties:
        type:
          description: The type of the video item, such as `movie`, `episode`, or `clip`.
        subtype:
          description: The subtype of the video item, such as `photo` when the video item is in a photo library
        key:
          description: The key at which the item's details can be fetched.  In many cases a metadata item may be passed without all the details (such as in a hub) and this key corresponds to the endpoint to fetch additional details.
        ratingKey:
          description: This is the opaque string to be passed into timeline, scrobble, and rating endpoints to identify them.  While it often appears to be numeric, this is not guaranteed.
        title:
          description: The title of the item (e.g. “300” or “The Simpsons”)
        titleSort:
          description: Whene present, this is the string used for sorting the item. It's usually the title with any leading articles removed (e.g. “Simpsons”).
        originalTitle:
          description: When present, used to indicate an item's original title, e.g. a movie's foreign title.
        year:
          type: integer
          description: When present, the year associated with the item's release (e.g. release year for a movie).
        index:
          type: integer
          description: When present, this represents the episode number for episodes, season number for seasons, or track number for audio tracks.
        absoluteIndex:
          type: integer
          description: When present, contains the disc number for a track on multi-disc albums.
        originallyAvailableAt:
          description: When present, in the format YYYY-MM-DD [HH:MM:SS] (the hours/minutes/seconds part is not always present). The air date, or a higher resolution release date for an item, depending on type. For example, episodes usually have air date like 1979-08-10 (we don't use epoch seconds because media existed prior to 1970). In some cases, recorded over-the-air content has higher resolution air date which includes a time component. Albums and movies may have day-resolution release dates as well.
        duration:
          type: integer
          description: When present, the duration for the item, in units of milliseconds.
        summary:
          description: When present, the extended textual information about the item (e.g. movie plot, artist biography, album review).
        tagline:
          description: When present, a pithy one-liner about the item (usually only seen for movies).
        thumb:
          description: When present, the URL for the poster or thumbnail for the item. When available for types like movie, it will be the poster graphic, but fall-back to the extracted media thumbnail.
        art:
          description: When present, the URL for the background artwork for the item.
        banner:
          description: When present, the URL for a banner graphic for the item.
        hero:
          description: When present, the URL for a hero image for the item.
        theme:
          description: When present, the URL for theme music for the item (usually only for TV shows).
        composite:
          description: When present, the URL for a composite image for descendent items (e.g. photo albums or playlists).
        studio:
          description: When present, the studio or label which produced an item (e.g. movie studio for movies, record label for albums).
        contentRating:
          description: If known, the content rating (e.g. MPAA) for an item.
        rating:
          type: number
          minimum: 0
          maximum: 10
          description: When present, the rating for the item. The exact meaning and representation depends on where the rating was sourced from.
        ratingImage:
          description: When present, indicates an image to be shown with the rating. This is passed back as a small set of defined URI values, e.g. rottentomatoes://image.rating.rotten.
        audienceRating:
          type: number
          minimum: 0
          maximum: 10
          description: Some rating systems separate reviewer ratings from audience ratings
        audienceRatingImage:
          description: A URI representing the image to be shown with the audience rating (e.g. rottentomatoes://image.rating.spilled).
        userRating:
          type: number
          minimum: 0
          maximum: 10
          description: When the user has rated an item, this contains the user rating
        viewOffset:
          type: integer
          description: When a user is in the process of viewing or listening to this item, this attribute contains the current offset, in units of milliseconds.
        viewCount:
          type: integer
          description: When a users has completed watched or listened to an item, this attribute contains the number of consumptions.
        lastViewedAt:
          type: integer
          description: When a user has watched or listened to an item, this contains a timestamp (epoch seconds) for that last consumption time.
        addedAt:
          type: integer
          description: In units of seconds since the epoch, returns the time at which the item was added to the library.
        updatedAt:
          type: integer
          description: In units of seconds since the epoch, returns the time at which the item was last changed (e.g. had its metadata updated).
        chapterSource:
          description: When present, indicates the source for the chapters in the media file. Can be media (the chapters were embedded in the media itself), agent (a metadata agent computed them), or mixed (a combination of the two).
        primaryExtraKey:
          description: Indicates that the item has a primary extra; for a movie, this is a trailer, and for a music track it is a music video. The URL points to the metadata details endpoint for the item.
        skipChildren:
          type: boolean
          description: When found on a show item, indicates that the children (seasons) should be skipped in favor of the grandchildren (episodes). Useful for mini-series, etc.
        skipParent:
          type: boolean
          description: When present on an episode or track item, indicates parent should be skipped in favor of grandparent (show).
        leafCount:
          type: integer
          description: For shows and seasons, contains the number of total episodes.
        viewedLeafCount:
          type: integer
          description: For shows and seasons, contains the number of viewed episodes.
        parentKey:
          type: string
          description: The `key` of the parent
        grandparentKey:
          type: string
          description: The `key` of the grandparent
        parentRatingKey:
          type: string
          description: The `ratingKey` of the parent
        grandparentRatingKey:
          type: string
          description: The `ratingKey` of the grandparent
        parentThumb:
          type: string
          description: The `thumb` of the parent
        grandparentThumb:
          type: string
          description: The `thumb` of the grandparent
        grandparentArt:
          type: string
          description: The `art` of the grandparent
        parentHero:
          type: string
          description: The `hero` of the parent
        grandparentHero:
          type: string
          description: The `hero` of the grandparent
        grandparentTheme:
          type: string
          description: The `theme` of the grandparent
        parentTitle:
          type: string
          description: The `title` of the parent
        grandparentTitle:
          type: string
          description: The `title` of the grandparent
        parentIndex:
          type: integer
          description: The `index` of the parent
        secondary:
          type: boolean
          description: Used by old clients to provide nested menus allowing for primative (but structured) navigation.
        prompt:
          type: string
          description: Prompt to give the user for this directory (such as `Search Movies`)
        search:
          type: boolean
          description: Indicates this is a search directory
        ratingCount:
          type: integer
          description: Number of ratings under this metadata
        Media:
          type: array
          items:
            $ref: '#/components/schemas/media'
        Image:
          type: array
          items:
            $ref: '#/components/schemas/image'
        Genre:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Country:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Guid:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Rating:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Director:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Writer:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Role:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Autotag:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        Filter:
          type: array
          description: Typically only seen in metadata at a library's top level
          items:
            $ref: '#/components/schemas/filter'
        Sort:
          type: array
          description: Typically only seen in metadata at a library's top level
          items:
            $ref: '#/components/schemas/sort'
      additionalProperties: true
    properties-MediaContainer:
      type: object
      properties:
        identifier:
          type: string
        size:
          type: integer
        totalSize:
          type: integer
          description: The total size of objects available.  Also provided in the X-Plex-Container-Total-Size header
        offset:
          type: integer
          description: The offset of where this container page starts among the total objects available.  Also provided in the X-Plex-Container-Start header
        Metadata:
          type: array
          items:
            $ref: '#/components/schemas/metadata'
      additionalProperties: true
    image:
      description: 'Images such as movie posters and background artwork are represented by Image elements.

        '
      type: object
      properties:
        type:
          type: string
          enum:
          - background
          - banner
          - clearLogo
          - coverPoster
          - snapshot
          description: Describes both the purpose and intended presentation of the image.
        url:
          type: string
          description: The relative path or absolute url for the image.
        alt:
          type: string
          description: Title to use for accessibility.
    directory:
      type: object
      properties:
        hubKey:
          type: string
        key:
          type: string
        title:
          type: string
        thumb:
          type: string
        art:
          type: string
        share:
          type: integer
        hasStoreServices:
          type: boolean
        hasPrefs:
          type: boolean
        identifier:
          type: string
        titleBar:
          type: string
        lastAccessedAt:
          type: integer
        type:
          type: string
        content:
          type: boolean
        filter:
          type: string
        Pivot:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              key:
                type: string
              type:
                type: string
              title:
                type: string
              context:
                type: string
              symbol:
                type: string
      additionalProperties: true
    tag:
      description: 'A variety of extra information about a metadata item is included as tags. These tags use their own element names such as `Genre`, `Writer`, `Directory`, and `Role`. Individual tag types may introduce their own extra attributes.

        '
      type: object
      properties:
        id:
          type: integer
        tag:
          description: The value of the tag (the name)
          example: Shaun Lawton
        tagKey:
          description: Plex identifier for this tag which can be used to fetch additional information from plex.tv
          example: 5d3ee12c4cde6a001c3e0b27
        tagType:
          type: integer
        filter:
          description: A filter parameter that can be used to query for more content that matches this tag value.
          example: actor=49
        role:
          description: The role this actor played
          example: Secretary
        thumb:
          example: http://image.tmdb.org/t/p/original/lcJ8qM51ClAR2UzXU1mkZGfnn3o.jpg
        context:
          type: string
        ratingKey:
          type: string
        confidence:
          type: number
          description: Measure of the confidence of an automatic tag
    mediaContainerWithPlaylistMetadata:
      type: object
      properties:
        MediaContainer:
          allOf:
          - $ref: '#/components/schemas/properties-MediaContainer'
          - type: object
            properties:
              Metadata:
                type: array
                items:
                  allOf:
                  - type: object
                    properties:
                      smart:
                        type: boolean
                        description: Whether or not the playlist is smart.
                      duration:
                        type: integer
                        description: The total duration of the playlist in ms
                      leafCount:
                        type: integer
                        description: The number of items in the playlist.
                      composite:
                        type: string
                        description: A composite image for the playlist.
                      key:
                        type: string
                        description: Leads to a list of items in the playlist.
                      playlistType:
                        type: string
                        enum:
                        - audio
                        - video
                        - photo
                        description: The type of the playlist.
                      specialPlaylistType:
                        type: string
                        description: If this is a special playlist, this returns its type (e.g. favorites).
                      readOnly:
                        type: boolean
                        description: If we return this as true then this playlist cannot be altered or deleted directly by the client.
                  - $ref: '#/components/schemas/metadata'
    stream:
      description: '`Stream` represents a particular stream from a media item, such as the video stream, audio stream, or subtitle stream. The stream may either be part of the file represented by the parent `Part` or, especially for subtitles, an external file. The stream contains more detailed information about the specific stream. For example, a video may include the `aspectRatio` at the `Media` level, but detailed information about the video stream like the color space will be included on the `Stream` for the video stream.  Note that photos do not have streams (mostly as an optimization).

        '
      type: object
      properties:
        audioChannelLayout:
          example: stereo
        bitDepth:
          type: integer
          example: 8
        bitrate:
          type: integer
          example: 5466
        canAutoSync:
          type: boolean
          description: For subtitle streams only. If `true` then the server can attempt to automatically sync the subtitle timestamps with the video.
          example: true
        chromaLocation:
          example: topleft
        chromaSubsampling:
          example: '4:2:0'
        codec:
          description: The codec of the stream, such as `h264` or `aac`
          example: h264
        colorPrimaries:
          example: bt709
        colorRange:
          example: tv
        colorSpace:
          example: bt709
        colorTrc:
          example: bt709
        default:
          type: boolean
          example: true
        displayTitle:
          description: A friendly name for the stream, often comprised of the language and codec information
          example: English (H.264 Main)
        frameRate:
          type: number
          example: 23.976
        hasScalingMatrix:
          example: false
        height:
          type: integer
          example: 544
        id:
          type: integer
          example: 1
        index:
          type: integer
          description: If the stream is part of the `Part` and not an external resource, the index of the stream within that part
          example: 0
        key:
          description: If the stream is independently streamable, the key from which it can be streamed
          example: /library/streams/1
        language:
          example: English
        languageCode:
          description: The three character language code for the stream contents
          example: eng
        level:
          type: integer
          example: 31
        profile:
          example: main
        refFrames:
          type: integer
          example: 2
        samplingRate:
          type: integer
          example: 48000
        selected:
          type: boolean
        streamIdentifier:
          type: integer
          example: 1
        streamType:
          type: integer
          description: A number indicating the type of the stream. `1` for video, `2` for audio, `3` for subtitles, `4` for lyrics
          example: 1
        width:
          type: integer
          example: 1280
      additionalProperties: true
  responses:
    slash-post-responses-200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/mediaContainerWithPlaylistMetadata'
          examples:
            playlist:
              description: A created playlist
              value:
                MediaContainer:
                  size: 1
                  Metadata:
                  - addedAt: 1476942219
                    composite: /playlists/2561805/composite/1485900004
                    duration: 1512000
                    key: /playlists/2561805/items
                    lastViewedAt: 1484680617
                    leafCount: 8
                    playlistType: video
                    ratingKey: '2561805'
                    smart: false
                    title: Background videos
                    type: playlist
                    updatedAt: 1485900004
                    viewCount: 8
    '400':
      description: Bad Request
      content:
        text/html:
          examples:
            badRequest:
              summary: A parameter has a bad value or required parameter is missing
              value: <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
  securitySchemes:
    user_token:
      type: apiKey
      in: header
      name: X-Plex-Token
      description: The token which identifies the user accessing the PMS.  This is typically provided to the client by plex.tv. This can be either a traditional access token or a JWT token obtained through the JWT authentication flow.
x-tagGroups:
- name: General
  tags:
  - General
  - Library
  - Library Playlists
  - Library Collections
  - Status
  - Activities
  - Updater
  - Butler
  - Events
  - Log
  - Preferences
  - Download Queue
  - UltraBlur
  - Transcoder
- name: Media Provider
  tags:
  - Provider
  - Metadata Agents
  - Content
  - Hubs
  - Search
  - Rate
  - Playlist
  - Play Queue
  - Timeline
- name: DVR
  tags:
  - DVRs
  - Devices
  - EPG
  - Subscriptions
  - Live TV
